name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint
      run: npm run lint

    - name: Build
      run: npm run build

  unit-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:unit

    - name: Archive test coverage
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: coverage-report
        path: coverage/

  e2e:
    runs-on: ubuntu-latest
    needs: [build, unit-test]

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run E2E tests
      run: npm run test:e2e:ci
      env:
        CI: true
        # Don't include real credentials in CI
        CYPRESS_INCLUDE_CREDENTIALS: 0
        VITE_EFILE_BASE_URL: 'https://api.mock.example.com/v4'
        # Mock Supabase for e2e tests
        VITE_SUPABASE_URL: 'https://mock-project.supabase.co'
        VITE_SUPABASE_ANON_KEY: 'mock-anon-key'

    - name: Archive test artifacts
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: cypress-screenshots
        path: |
          cypress/screenshots
          cypress/videos